In [1]:
import numpy as np

In [2]:
# Create a vector as a row
vector_row = np.array([1, 2, 3])
# Create a vector as a column
vector_column = np.array([[1],
                          [2],
                          [3]])
print(vector_row)
print(vector_column)

[1 2 3]
[[1]
 [2]
 [3]]


In [3]:
#NumPy actually has a dedicated matrix data structure
matrix_object = np.mat([[1, 2],
[1, 2],
[1, 2]])
print(matrix_object)

[[1 2]
 [1 2]
 [1 2]]


In [4]:
# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])
# Create matrix
matrix = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

In [5]:
vector[2]

3

In [6]:
matrix[1][1]

5

In [7]:
matrix[2][0]

7

In [8]:
# Select all elements of a vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [9]:
# Select everything up to and including the third element
vector[:3]

array([1, 2, 3])

In [10]:
# Select everything after the third element
vector[3:]

array([4, 5, 6])

In [11]:
# Select the last element
vector[-1]

6

In [12]:
# Select the first two rows and all columns of a matrix
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
matrix[1:2,1:2]

array([[5]])

In [14]:
# Select all rows and the second column
matrix[:,1:2]

array([[2],
       [5],
       [8]])

In [15]:
matrix = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

In [16]:
matrix.shape

(3, 4)

In [17]:
matrix.size

12

In [18]:
matrix.ndim

2